language: python
cache: pip

# Test environments
matrix:
  include:
   - env: TOXENV=py33
     python: 3.3
   - env: TOXENV=py34
     python: 3.4
   - env: TOXENV=py35
     python: 3.5

# Package installation
before_install:
  - sudo apt-get install libcap2-bin python3-pip
  - sudo cp `python3 -c "import sys; print(sys.executable)"` /usr/bin/python_boxed
  - sudo setcap cap_setuid+ep /usr/bin/python_boxed
  - sudo python3 setup.py install

install:
  - pip install tox coveralls

# Run tests
script:
  tox

# Register code coverage in coveralls
after_success:
  cp /tmp/boxed/.coverage . &&  coveralls
