language: python
cache: pip
sudo: false

# Test environments
matrix:
  include:
   - env: TOXENV=py33
     python: 3.3
   - env: TOXENV=py34
     python: 3.4
   - env: TOXENV=py35
     python: 3.5

# Package installation
install:
  - python setcap.py
  - pip install tox coveralls

# Run tests
script:
  tox

# Register code coverage in coveralls
after_success:
  cp /tmp/boxed/.coverage . &&  coveralls
