language: python
cache: pip

# Test environments
matrix:
  include:
   - env: TOXENV=py33
     python: 3.3
   - env: TOXENV=py34
     python: 3.4
   - env: TOXENV=py35
     python: 3.5

# Package installation
before_install:
  - sudo python setcap.py

install:
  - pip install tox coveralls

# Run tests
script:
  tox

# Register code coverage in coveralls
after_success:
  cp /tmp/boxed/.coverage . &&  coveralls
